# Generated by Django 3.1.6 on 2021-03-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='blogpost',
        ),
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
