# Generated by Django 3.1.6 on 2021-03-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
